name: football_commentary_app
description: "A Flutter football commentary app with voice chat rooms."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # utilities
  path_provider: ^2.1.5 # for accessing device storage
  permission_handler: ^12.0.0+1 # for handling permissions
  url_launcher: ^6.3.1 # for external urls opening
  freezed_annotation: ^3.0.0 # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_annotation: ^4.9.0 # Automatically generate code for converting to and from JSON by annotating Dart classes

  # UI
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  flutter_native_splash: ^2.4.6
  
  # Networking
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  pretty_dio_logger: ^1.4.0
  internet_connection_checker: ^3.0.1 # For checking actual internet connectivity

  # Localization
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
    
  # Assets
  flutter_svg: ^2.2.0

  # Authentication
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.3

  # State Management
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.0.0
  bloc: ^9.0.0
  equatable: ^2.0.7

  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0 # For secure token storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0 # Flutter extensions for Hive

  # Dependency Injection
  get_it: ^8.0.3

  # Others
  sentry_flutter: ^8.14.2
  dartz: ^0.10.1
  modal_progress_hud_nsn: ^0.5.1

  # Environment Variables
  flutter_dotenv: ^5.2.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_database: ^11.1.6 # Firebase Realtime Database
  flutter_local_notifications: ^19.1.0

  # Agora Voice SDK
  agora_rtc_engine: ^6.3.2

  # easy way to add shimmer effect
  shimmer: ^3.0.0

  fluttertoast: ^8.2.12
  flutter_portal: ^1.1.4

  # animations
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.4.15 # A build system for Dart code generation and modular compilation
  freezed: ^3.0.6 # Code generator (mainly used with cubit & retrofit)
  json_serializable: ^6.9.5 # Automatically generate code for converting to and from JSON by annotating Dart classes
  retrofit_generator: ^9.2.0 # Code generator (mainly used with cubit & retrofit)
  mockito: ^5.4.6
  bloc_test: ^10.0.0

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
    - .env
    - example.env

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

flutter_intl:
  enabled: true
  main_locale: en

